"""Appointo — a compact scheduling application for a small team."""

from __future__ import annotations

import os
import sqlite3
from collections.abc import Mapping
from datetime import date, datetime
from pathlib import Path
from typing import Any

import psycopg
from flask import Flask, abort, flash, g, redirect, render_template, request, send_from_directory, url_for
from psycopg.rows import dict_row


STATUSES = ("scheduled", "completed", "cancelled")


class Database:
    """Small adapter that keeps the application's SQL portable between SQLite and Postgres."""

    def __init__(self, connection: Any, *, is_postgres: bool) -> None:
        self.connection = connection
        self.is_postgres = is_postgres

    def execute(self, query: str, params: tuple[Any, ...] | list[Any] = ()) -> Any:
        if self.is_postgres:
            query = query.replace("?", "%s")
        return self.connection.execute(query, params)

    def executemany(self, query: str, params: list[tuple[Any, ...]]) -> Any:
        if self.is_postgres:
            query = query.replace("?", "%s")
            with self.connection.cursor() as cursor:
                return cursor.executemany(query, params)
        return self.connection.executemany(query, params)

    def executescript(self, script: str) -> None:
        for statement in script.split(";"):
            if statement.strip():
                self.execute(statement)

    def commit(self) -> None:
        self.connection.commit()

    def close(self) -> None:
        self.connection.close()


def create_app(test_config: dict | None = None) -> Flask:
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if database_url.startswith("postgres://"):
        database_url = database_url.replace("postgres://", "postgresql://", 1)

    # Vercel serves public/ at the site root. The local fallback route below serves it in development.
    app = Flask(__name__, instance_relative_config=True, static_folder=None)
    app.config.from_mapping(
        SECRET_KEY=os.environ.get("APPOINTO_SECRET", "development-only-secret"),
        DATABASE_URL=database_url,
        DATABASE=os.path.join(app.instance_path, "appointments.sqlite3"),
    )
    if test_config:
        app.config.update(test_config)

    if not app.config["DATABASE_URL"]:
        Path(app.instance_path).mkdir(parents=True, exist_ok=True)

    @app.teardown_appcontext
    def close_db(_error: BaseException | None = None) -> None:
        db = g.pop("db", None)
        if db is not None:
            db.close()

    def get_db() -> Database:
        if "db" not in g:
            if app.config["DATABASE_URL"]:
                g.db = Database(
                    psycopg.connect(app.config["DATABASE_URL"], row_factory=dict_row),
                    is_postgres=True,
                )
            else:
                connection = sqlite3.connect(app.config["DATABASE"])
                connection.row_factory = sqlite3.Row
                g.db = Database(connection, is_postgres=False)
        return g.db

    def initialise_db() -> None:
        db = get_db()
        id_column = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if db.is_postgres else "INTEGER PRIMARY KEY AUTOINCREMENT"
        db.executescript(
            f"""
            CREATE TABLE IF NOT EXISTS appointments (
                id {id_column},
                title TEXT NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                appointment_date TEXT NOT NULL,
                start_time TEXT NOT NULL,
                end_time TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'scheduled'
                    CHECK (status IN ('scheduled', 'completed', 'cancelled')),
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX IF NOT EXISTS idx_appointments_date_status
                ON appointments (appointment_date, status);
            """
        )
        if db.execute("SELECT COUNT(*) AS count FROM appointments").fetchone()["count"] == 0:
            db.executemany(
                """
                INSERT INTO appointments
                    (title, description, appointment_date, start_time, end_time, status)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                [
                    (
                        "Design review",
                        "Review the Appointo user flow with the product team.",
                        "2026-09-14",
                        "09:30",
                        "10:15",
                        "scheduled",
                    ),
                    (
                        "Client onboarding",
                        "Walk the new client through their first-week checklist.",
                        "2026-09-14",
                        "11:00",
                        "12:00",
                        "completed",
                    ),
                    (
                        "Weekly planning",
                        "Set priorities and owners for the coming week.",
                        "2026-09-15",
                        "14:00",
                        "14:45",
                        "cancelled",
                    ),
                ],
            )
        db.commit()

    def appointment_or_404(appointment_id: int) -> Mapping[str, Any]:
        appointment = get_db().execute(
            "SELECT * FROM appointments WHERE id = ?", (appointment_id,)
        ).fetchone()
        if appointment is None:
            abort(404)
        return appointment

    def time_slot_is_available(
        appointment_date: str, start_time: str, end_time: str, appointment_id: int | None = None
    ) -> bool:
        """Return false for any overlapping non-cancelled appointment on the same day."""
        query = """
            SELECT 1 FROM appointments
            WHERE appointment_date = ?
              AND status != 'cancelled'
              AND start_time < ?
              AND end_time > ?
        """
        params: list[object] = [appointment_date, end_time, start_time]
        if appointment_id is not None:
            query += " AND id != ?"
            params.append(appointment_id)
        return get_db().execute(query, params).fetchone() is None

    def validate_form(form: dict[str, str], appointment_id: int | None = None) -> list[str]:
        errors: list[str] = []
        if not form["title"]:
            errors.append("A title is required.")
        elif len(form["title"]) > 100:
            errors.append("The title must be 100 characters or fewer.")
        if len(form["description"]) > 500:
            errors.append("The description must be 500 characters or fewer.")

        valid_date = valid_times = False
        try:
            datetime.strptime(form["appointment_date"], "%Y-%m-%d")
            valid_date = True
        except ValueError:
            errors.append("Choose a valid appointment date.")
        try:
            start = datetime.strptime(form["start_time"], "%H:%M")
            end = datetime.strptime(form["end_time"], "%H:%M")
            valid_times = True
            if end <= start:
                errors.append("End time must be after start time.")
        except ValueError:
            errors.append("Choose a valid start and end time.")

        if valid_date and valid_times and not errors and not time_slot_is_available(
            form["appointment_date"], form["start_time"], form["end_time"], appointment_id
        ):
            errors.append("That time overlaps an existing active appointment.")
        return errors

    def form_values(source: Mapping[str, Any] | None = None) -> dict[str, str]:
        if source is not None:
            return {key: source[key] for key in ("title", "description", "appointment_date", "start_time", "end_time")}
        return {
            "title": "",
            "description": "",
            "appointment_date": date.today().isoformat(),
            "start_time": "09:00",
            "end_time": "09:30",
        }

    @app.template_filter("friendly_date")
    def friendly_date(value: str) -> str:
        return datetime.strptime(value, "%Y-%m-%d").strftime("%a, %b %-d")

    @app.template_filter("friendly_time")
    def friendly_time(value: str) -> str:
        return datetime.strptime(value, "%H:%M").strftime("%-I:%M %p")

    @app.context_processor
    def expose_today() -> dict[str, str]:
        return {"today": date.today().isoformat()}

    @app.get("/style.css")
    def stylesheet():
        return send_from_directory(Path(app.root_path) / "public", "style.css")

    @app.get("/")
    def board():
        selected_date = request.args.get("date", "").strip()
        selected_status = request.args.get("status", "all").strip().lower()
        if selected_status not in (*STATUSES, "all"):
            selected_status = "all"

        clauses, params = [], []
        if selected_date:
            try:
                datetime.strptime(selected_date, "%Y-%m-%d")
                clauses.append("appointment_date = ?")
                params.append(selected_date)
            except ValueError:
                flash("The date filter was ignored because it is not valid.", "error")
                selected_date = ""
        if selected_status != "all":
            clauses.append("status = ?")
            params.append(selected_status)
        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        appointments = get_db().execute(
            f"SELECT * FROM appointments {where} ORDER BY appointment_date, start_time, id", params
        ).fetchall()

        counts = {
            row["status"]: row["count"]
            for row in get_db()
            .execute("SELECT status, COUNT(*) AS count FROM appointments GROUP BY status")
            .fetchall()
        }
        return render_template(
            "board.html",
            appointments=appointments,
            selected_date=selected_date,
            selected_status=selected_status,
            counts=counts,
        )

    @app.route("/appointments/new", methods=("GET", "POST"))
    def new_appointment():
        values = form_values()
        if request.method == "POST":
            values = {key: request.form.get(key, "").strip() for key in values}
            errors = validate_form(values)
            if not errors:
                get_db().execute(
                    """
                    INSERT INTO appointments (title, description, appointment_date, start_time, end_time)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    tuple(values[key] for key in values),
                )
                get_db().commit()
                flash("Appointment added to the board.", "success")
                return redirect(url_for("board"))
            for error in errors:
                flash(error, "error")
        return render_template("appointment_form.html", values=values, mode="Create", appointment=None)

    @app.route("/appointments/<int:appointment_id>/edit", methods=("GET", "POST"))
    def edit_appointment(appointment_id: int):
        appointment = appointment_or_404(appointment_id)
        values = form_values(appointment)
        if request.method == "POST":
            values = {key: request.form.get(key, "").strip() for key in values}
            errors = validate_form(values, appointment_id)
            if not errors:
                get_db().execute(
                    """
                    UPDATE appointments
                    SET title = ?, description = ?, appointment_date = ?, start_time = ?, end_time = ?
                    WHERE id = ?
                    """,
                    (*tuple(values[key] for key in values), appointment_id),
                )
                get_db().commit()
                flash("Appointment updated.", "success")
                return redirect(url_for("board"))
            for error in errors:
                flash(error, "error")
        return render_template("appointment_form.html", values=values, mode="Edit", appointment=appointment)

    @app.post("/appointments/<int:appointment_id>/<action>")
    def change_status(appointment_id: int, action: str):
        appointment = appointment_or_404(appointment_id)
        if action not in {"complete", "cancel"}:
            abort(404)
        desired_status = "completed" if action == "complete" else "cancelled"
        if appointment["status"] != "scheduled":
            flash(f"Only scheduled appointments can be {desired_status}.", "error")
        else:
            get_db().execute("UPDATE appointments SET status = ? WHERE id = ?", (desired_status, appointment_id))
            get_db().commit()
            flash(f"Appointment marked as {desired_status}.", "success")
        return redirect(url_for("board"))

    with app.app_context():
        initialise_db()

    return app


app = create_app()


if __name__ == "__main__":
    app.run(debug=True)
